### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Sebastian-Mynott** [VascoElbrecht/PrimerMiner#26]
Hi Vasco,

I'm keen to give PrimerMiner a try but have run into an issue. When installing, I get the following Warnings and Error:

`> install.packages("~/Downloads/PrimerMiner-0.12.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from ‘/Users/sebastian/Downloads/PrimerMiner-0.12.tar.gz’
Warning in install.packages :
  installation of package ‘/Users/sebastian/Downloads/PrimerMiner-0.12.tar.gz’ had non-zero exit status`

Any idea wha I might be doing wrong?

Many thanks,
Sebastian

**Comment by VascoElbrecht** [comment]
Dear Sebastian,

Thank you for your request.

Yes, files downloaded from Github are compressed. You have to "unzip" the folder. On mac, just double click on the downloaded file. Then you can access the folder contents and it should install without any issues.

Please let me know if that works or if you need further assistance.

Best
Vasco

**Comment by Sebastian-Mynott** [comment]
Dear Vasco,

Thank you for your prompt response. I did try installing the ‘unzipped' package without success.

> install.packages("~/Applications/R Packages/PrimerMiner-0.12", repos = NULL, type = "source")
Warning: invalid package ‘/Users/sebastian/Applications/R Packages/PrimerMiner-0.12’
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘/Users/sebastian/Applications/R Packages/PrimerMiner-0.12’ had non-zero exit status
> install.packages("~/Applications/R Packages/PrimerMiner-0.12/PrimerMiner", repos = NULL, type = "source")
Warning: invalid package ‘/Users/sebastian/Applications/R Packages/PrimerMiner-0.12/PrimerMiner’
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘/Users/sebastian/Applications/R Packages/PrimerMiner-0.12/PrimerMiner’ had non-zero exit status

I’m running R 3.3.1 in RStudio on macOS Sierra, if that helps.

Many thanks.

Sebastian

**Comment by VascoElbrecht** [comment]
Hello Sebastian,

Can you please try changing the working directory first with

`setwd("~/Applications/R Packages/PrimerMiner-0.12/")`

And then try installing the package again using

install.packages("PrimerMiner", repos = NULL, type="source", dependencies=T)

Best
Vasco

**Comment by Sebastian-Mynott** [comment]
Hi Vasco,

That’s got it. Many thanks for your support!

I’m sorry if I caused you any frustration.

Best 
Sebastian

**Comment by VascoElbrecht** [comment]
Hello Sebastian,

I'm happy to help. Let me know if you run into any other issues!

Best
Vasco
