### ISSUE TITLE
Design Primers

### ISSUE THREAD

**Issue by marcomeola** [VascoElbrecht/PrimerMiner#37]
Maybe I got it wrong but does PrimerMiner design primers as well? I couldn't find any tutorial in the wiki...

**Comment by VascoElbrecht** [comment]
hey, unfortunately PrimerMiner does not design primers automatically, just downloads the sequences and if you like generates visualizations that allow you to design the primers manually. Metabarcoding sequences are often too variable for automated primer design =)
